<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="OLSCHN-PC-0229-new" name="com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning" tests="5" failures="0" timestamp="18 Sep 2019 09:36:31 GMT" time="562.949" errors="1">
  <testcase name="testMyLearningPageClassroom" time="226.734" classname="com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.wv.auto.framework.utils.Reporter.writeFailure(Reporter.java:104)
at com.wv.auto.framework.utils.Reporter.writeSummary(Reporter.java:82)
at com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning.testMyLearningPageClassroom(WebTestsMyLearning.java:178)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testMyLearningPageClassroom -->
  <testcase name="testMyLearningPage1" time="80.435" classname="com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning"/>
  <testcase name="testMyLearningPage0" time="49.908" classname="com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning"/>
  <testcase name="testMyLearningPage2" time="147.438" classname="com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning"/>
  <testcase name="testMyLearningPage3" time="58.434" classname="com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning"/>
</testsuite> <!-- com.origin.fractal.testauto.test.testsuites.WebTestsMyLearning -->
